CREATE DATABASE IF NOT EXISTS xmen;
USE xmen;

CREATE TABLE IF NOT EXISTS experiments (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE,
    root TEXT NOT NULL,
    status TEXT NOT NULL,
    user TEXT NOT NULL,
    added TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data JSON NOT NULL);

CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE,
    user MEDIUMTEXT NOT NULL,
    salt BLOB NOT NULL,
    password BLOB NOT NULL,
    added TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
